[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/behance/*"
  to = "/.netlify/functions/behance/:splat"
  status = 200

[[redirects]]
  from = "/api/behance"
  to = "/.netlify/functions/behance"
  status = 200

[[redirects]]
  from = "/api/artstation"
  to = "/.netlify/functions/artstation"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
